services:
  - type: web
    name: knowyourcity-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20.19.0
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
